---
title: "R CODES"
output: pdf_document
mainfont: "Times New Roman"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Input and Libraries
```{r, results='hide',warning=FALSE,message=FALSE}
data6 <- read.csv("data6.csv")
data6$fueltype <- as.factor(data6$fueltype)
data6$tranmission<- as.factor(data6$tranmission)
attach(data6)
library(ggplot2)
library(MASS)
library(AID)
library(dplyr)
library(tigerstats)
library(onewaytests)
library(DAAG)
library(lattice)
library(lubridate)
library(tidyverse)
library(broom)
library(car)
library(rcompanion)
```
# Sampling Methods
[Appendix A1]
```{r, results='hide'}
under18 <- subset(data6,age<18)
over18 <- subset(data6,age>=18)
# for under18
#Simple random sampling
library(tigerstats)

set.seed(250)

s1 <- popsamp(3,under18)
s2 <- popsamp(3,under18)

a0 <-mean(under18$tax)

a1 <- mean(s1$tax)
a7 <- mean(s2$tax)

# systematic sampling

set.seed(250)

systematic.sampling1<-c()
for (i in 1:nrow(under18)) {
  if (i %% 3==0) {
    systematic.sampling1= rbind(systematic.sampling1,under18[i,])
  }
}
a2 <- mean(systematic.sampling1$tax)

systematic.sampling2<-c()
for (i in 1:nrow(under18)) {
  if (i %% 4==0) {
    systematic.sampling2= rbind(systematic.sampling2,under18[i,])
  }
}
a5 <- mean(systematic.sampling2$tax)

# STRATIFIED RANDOM SAMPLING

automatic=subset(under18,tranmission=="1")
manuel=subset(under18,tranmission=="2")
semi=subset(under18,tranmission=="3")
other=subset(under18,tranmission=="4")

set.seed(250)

auto.samp=popsamp(2,automatic)
manuel.samp=popsamp(2,manuel)
semi.samp =popsamp(2,semi)
other.samp=popsamp(2,other)

stratified.sample<-rbind(auto.samp,manuel.samp,semi.samp,other.samp)
a3 <- mean(stratified.sample$tax)

auto.samp1=popsamp(3,automatic)
manuel.samp2=popsamp(3,manuel)
semi.samp3 =popsamp(3,semi)
other.samp4=popsamp(3,other)

stratified.sample2<-rbind(auto.samp1,manuel.samp2,semi.samp3,other.samp4)
a6 <- mean(stratified.sample2$tax)

# Cluster Sampling
a4 <- mean(automatic$tax)
a8 <- mean(manuel$tax)
cat("Means of Samples:",cbind(a1,a2,a3,a4,a5,a6,a7,a8))
```
[Appendix A2]
```{r, results='hide'}
e1<-a0-a1
e2<-a0-a2
e3<-a0-a3
e4<-a0-a4
e5<-a0-a5
e6<-a0-a6
e7<-a0-a7
e8<-a0-a8
sampling.error<-cbind(e1,e2,e3,e4,e5,e6,e7,e8)
cat("Sampling Errors:",sampling.error)
```
[Appendix A3]
```{r, results='hide'}
#3 
#Simple random sampling

set.seed(250)

ss1 <- popsamp(3,over18)
ss2 <- popsamp(3,over18)

aa0 <-mean(over18$tax)

aa1 <- mean(ss1$tax)
aa7 <- mean(ss2$tax)

# systematic sampling

set.seed(250)

systematic.sampling3<-c()
for (i in 1:nrow(over18)) {
  if (i %% 3==0) {
    systematic.sampling3= rbind(systematic.sampling3,over18[i,])
  }
}
aa2 <- mean(systematic.sampling3$tax)

systematic.sampling4<-c()
for (i in 1:nrow(over18)) {
  if (i %% 4==0) {
    systematic.sampling4= rbind(systematic.sampling4,over18[i,])
  }
}
aa5 <- mean(systematic.sampling4$tax)

# STRATIFIED RANDOM SAMPLING

automatic1=subset(over18,tranmission=="1")
manuel1=subset(over18,tranmission=="2")
semi1=subset(over18,tranmission=="3")
other1=subset(over18,tranmission=="4")

set.seed(250)

auto.sampp=popsamp(2,automatic1)
manuel.sampp=popsamp(2,manuel1)
semi.sampp =popsamp(2,semi1)
other.sampp=popsamp(2,other1)

stratified.sample3<-rbind(auto.sampp,manuel.sampp,semi.sampp,other.sampp)
aa3 <- mean(stratified.sample3$tax)

auto.sampp1=popsamp(3,automatic1)
manuel.sampp2=popsamp(3,manuel1)
semi.sampp3 =popsamp(3,semi1)
other.sampp4=popsamp(3,other1)

stratified.sample4<-rbind(auto.sampp1,manuel.sampp2,semi.sampp3,other.sampp4)
aa6 <- mean(stratified.sample4$tax)


# Cluster Sampling

aa4 <- mean(automatic1$tax)
aa8 <- mean(manuel1$tax)
cat("Means of Samples:",cbind(aa1,aa2,aa3,aa4,aa5,aa6,aa7,aa8))
```
[Appendix A4]
```{r, results='hide'}

ee1<-aa0-aa1
ee2<-aa0-aa2
ee3<-aa0-aa3
ee4<-aa0-aa4
ee5<-aa0-aa5
ee6<-aa0-aa6
ee7<-aa0-aa7
ee8<-aa0-aa8
sampling.error2<-cbind(ee1,ee2,ee3,ee4,ee5,ee6,ee7,ee8)
cat("Sampling Errors:",sampling.error2)
```
[Appendix A5]
```{r, results='hide'}
summary(data6)
```
# First Research Question  
# Simple Linear Regression Model
[Appendix B1]   
```{r, results='hide'}

lm1=lm(price~mileage,data = data6)
summary(lm1)
cor(data6$price,data6$mileage)

```
[Appendix B2][Figure 1]:    
```{r, results='hide',fig.show='hide'}
par(mfrow=c(1,2))
plot(mileage,price,xlab ="mileage",ylab="price",pch=16)
abline(lm1)

yhat=predict(lm1)  
resid=lm1$residuals
plot(yhat,resid,pch=16,xlab="fitted values",ylab="residuals")
abline(h=0)
```
[Appendix B3][Figure 2]
```{r, results='hide', out.width = "360px",fig.show='hide'}
qqnorm(resid)
qqline(resid)
shapiro.test(data6$price)
```
[Appendix B4]
```{r, results='hide', out.width = "360px"}
data6$price <- data6$price**0.48
shapiro.test(data6$price)
```
[Appendix B5]
```{r, results='hide', out.width = "360px"}
lm1=lm(price~mileage,data = data6)
anova(lm1)
```
[Appendix B6]
```{r, results='hide'}
summary(lm1)
```
[Appendix B7]
```{r, results='hide'}
confint(lm1, level=0.90)
```
[Appendix B8]   
```{r, results='hide'}
cor(data6$mileage,data6$price)
```
[Appendix B9]    
```{r, results='hide'}
predict(lm1,data.frame(mileage=10000))  
```
# Multiple Linear Regression    
[Appendix B10][Figure 3]
```{r, results='hide', message=FALSE, out.width = "250px", fig.align='center',fig.show='hide'}
themodel=lm(price~mileage+mpg,data=data6)
summary(themodel)
cat("The correlation coefficient between mpg and price:",cor(data6$mpg,data6$price))
cat("The correlation coefficient between mileage and price:",cor(data6$mileage,data6$price))

ggplot(data6, aes(x=mileage, y=price)) + geom_point(color="blue")
```
[Appendix B11][Figure 4]
```{r, results='hide', out.width = "250px", fig.align='center',fig.show='hide'}
ggplot(data6, aes(x=mpg, y=price)) + geom_point(color="orange")
```
# Diagnostic Checks   
[Appendix B12][Figure 5]    
```{r, results='hide',fig.show='hide'}
data6 <- read.csv("data6.csv")
par(mfrow=c(1,2))
hist(data6$price,col="darkmagenta",main = "For Price",xlab = "Price")
hist(data6$price**0.48,col="gold",main = "For Transformed Price",xlab = "Price")
print("p-value for the price:")
shapiro.test(data6$price)[2]
print("p-value for the transformed price:")
shapiro.test(data6$price**0.48)[2]
```
[Appendix B13][Figure 6]   
```{r, results='hide',fig.show='hide'}
data6$price <- data6$price**0.48
themodel2=lm(price~mileage+mpg,data=data6)
par(mfrow=c(2,2))
plot(themodel2)
```
# The Multicollinearity Check
[Appendix B14]
```{r, results='hide'}
vif(themodel)
```
[Appendix B15]   
```{r, results='hide'}
summary(themodel2)[9]
```
[Appendix B16][Figure 7]    
```{r, results='hide', out.width = "490px",fig.show='hide'}
par(mfrow=c(2,2))
plot(themodel2)
```
[Appendix B17][Figure 8]
```{r, results='hide', out.width = "360px", fig.align='center',fig.show='hide'}
plot(themodel2,4) 
```

# Second Research Question    
```{r, results='hide'}
data6 <- read.csv("data6.csv")
data6$fueltype <- as.factor(data6$fueltype)

```
[Appendix C1][Figure 9]
```{r, results='hide', out.width = "250px",warning=FALSE, fig.align='center',fig.show='hide'}
ggplot(data6) +
  aes(x = tranmission, y = price) +
  geom_boxplot(color="blue")

```
[Appendix C2]
```{r, results='hide'}
automaticdata <- subset(data6,tranmission =="1")
shapiro.test(automaticdata$price)
```
[Appendix C3][Figure 10]
```{r, results='hide', out.width = "360px",fig.show='hide'}
boxcoxnc(automaticdata$price)
shapiro.test(automaticdata$price**0.44)
```
[Appendix C4]
```{r, results='hide'}
automaticdata$price <- automaticdata$price**0.44
manueldata <- subset(data6,tranmission =="2")
shapiro.test(manueldata$price)
```
[Appendix C5]
```{r, results='hide', out.width = "360px"}
shapiro.test(manueldata$price**0.55)
manueldata$price <- manueldata$price**0.55 

```
[Appendix C6]
```{r, results='hide'}
myautomaticdata <- as.numeric(automaticdata$price)
mymanueldata <- as.numeric(manueldata$price)

```
[Appendix C7]
```{r, results='hide'}
var.test(myautomaticdata,mymanueldata)[3]
```
[Appendix C8]
```{r, results='hide'}
t.test(myautomaticdata,mymanueldata,alternative="less",conf.level = 0.95,var.equal = FALSE)

```
# Third Research Question     
# Assumption Checks     
[Appendix D1]   
```{r, results='hide'}
anova <- aov(price ~ fueltype, data = data6)

shapiro.test(residuals(anova))
```
[Appendix D2][Figure 11]
```{r, results='hide', out.width = "360px",fig.show='hide'}
plot(anova,2)
```
[Appendix D3]
```{r, results='hide'}
shapiro.test(data6$price)
```
[Appendix D4][Figure 112]
```{r, results='hide', out.width = "360px",fig.show='hide'}
plot(anova, 1)
```
[Appendix A]    
```{r, results='hide'}
bartlett.test(price ~ fueltype, data = data6)
```
[Appendix D5][Figure 13]
```{r, results='hide', out.width = "250px", fig.align='center',fig.show='hide'}
data6$price <- data6$price**0.48 
qplot(as.factor(data6$fueltype),data6$price,geom = "boxplot")+labs(title="Box plot of price w.r.t fueltype",x="fueltype", y = "price")

```
# Anova
[Appendix D6]
```{r, results='hide'}
anova <- aov(price ~ fueltype, data = data6)
summary(anova)

```
[Appendix D7]
```{r, results='hide'}
TukeyHSD(anova)
```

Non Parametric Approach :    
```{r, results='hide'}
data6 <- read.csv("data6.csv")
data6$fueltype <- as.factor(data6$fueltype)
data6$tranmission<- as.factor(data6$tranmission)
```
[Appendix D8][Figure 1]       
```{r, results='hide',fig.show='hide'}
kruskal.test(price ~ fueltype, data = data6)[3]
```
[Appendix D9]
```{r, results='hide'}
pairwise.wilcox.test(data6$price, data6$fueltype,
                     p.adjust.method = "BH")
```
# Fourth Research Question    

```{r, results='hide'}
set.seed(250)

srs <- popsamp(60,data6)

agedata <- data6$age
agedata <- as.numeric(agedata)

```
[Appendix E1]
```{r, results='hide'}
shapiro.test(agedata)
```
[Appendix E2]
```{r, results='hide'}
mu0 <- 20
t.test(agedata,alternative = "less",mu=20,conf.level = 0.95)[3]
```
[Appendix E3]
```{r, results='hide'}
sample.mean <- mean(agedata)
cat("Point Estimation :",sample.mean,"\n")

sample.n <- length(agedata)
sample.sd <- sd(agedata)
sample.se <- sample.sd/sqrt(sample.n)
print(sample.se)

alpha = 0.05
degrees.freedom = sample.n - 1
t.score = qt(p=alpha/2, df=degrees.freedom,lower.tail=F)
print(t.score)
margin.error <- t.score * sample.se

lower.bound <- sample.mean - margin.error
upper.bound <- sample.mean + margin.error
cat("Interval Estimation :",lower.bound,",",upper.bound,"\n")

```
# Fifth Research Question   
[Appendix F1]
```{r, results='hide',  message=FALSE}
nl <- subset(data6,price<36000 & age<18)
ml <- subset(data6,price<36000 & age>=18)
kn <- subset(data6,price>=36000 & age<18)
kl <- subset(data6,price>=36000 & age>=18)

contingecy_table <- matrix(rbind(nrow(nl),nrow(kn),nrow(ml),nrow(kl)),2)
colnames(contingecy_table) <- c("Age <18","Age >18")
rownames(contingecy_table) <- c("Price <36000","Price >36000")

contingecy_table

chisq.test(contingecy_table)
coltotals=apply(contingecy_table,2,sum)

apply(contingecy_table,1,"/",coltotals)
```
[Appendix F2]  
```{r, results='hide'}
cramerV(contingecy_table)
```
